# Site settings
name: Seongwon Yang
email: ysw991106
url: https://Seongwon-developer.github.io
description: "A blog and a portfolio"
author: "author"
title: "Seongwon-developer-BlogFolio"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: Seongwon-developer

# twitter:
#   username: username
